global_scan_settings:
  concurrent_scanners: 50
  default_output_path: "./discovered_devices.json"
  max_oids_per_snmp_request: 60
  default_dns_servers:
    - "1.1.1.1:53"
    - "8.8.8.8:53"

targets:
  - name: "target-network"
    addresses:
      - "192.168.100.1-192.168.100.10"
    profile_name: "icmp-only-profile"

snmp_configs:
  - name: "public-v2c"
    version: "v2c"
    community: "public"
    timeout_seconds: 5
    retries: 1
  
  - name: "secure-v3-authpriv"
    version: "v3"
    username: "adminUser"
    security_level: "authPriv"
    auth_protocol: "SHA"
    auth_password: "authPassword123"
    priv_protocol: "AES"
    priv_password: "privPassword123"
    timeout_seconds: 10
    retries: 2

profiles:
  - name: "full-scan-profile"
    icmp:
      is_enabled: true
      timeout_seconds: 2
      retries: 3
      packet_size_bytes: 56
      privileged: false
      skip_if_unreachable: true
    snmp:
      is_enabled: true
      config_names_ordered:
        - "secure-v3-authpriv"
        - "public-v2c"
      oids_to_query:
        - "1.3.6.1.2.1.1.1.0" # sysDescr
        - "1.3.6.1.2.1.1.5.0" # sysName
        - "1.3.6.1.2.1.2.1.0" # ifNumber
    dns:
      is_enabled: true
      do_reverse_lookup: true
      do_forward_lookup_if_reverse_found: true
      timeout_seconds: 3

  - name: "icmp-only-profile"
    icmp:
      is_enabled: true
      timeout_seconds: 5
      retries: 5
      packet_size_bytes: 56
      privileged: true
      skip_if_unreachable: true
    snmp:
      is_enabled: false
    dns:
      is_enabled: false