# .github/workflows/linter.yml

name: Lint Code Base

on:
  push: # Runs on pushes to specified branches
    branches: [ main, master, develop ] # Adjust to your project's main branches
  pull_request: # Runs on pull requests targeting specified branches
    branches: [ main, master, develop ] # Adjust to your project's main branches

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          # Only validate certain codebase parts
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: true
          VALIDATE_GO_MODULES: true
          VALIDATE_YAML: true
          # Disable error on no files to lint
          ERROR_ON_MISSING_EXEC_BIT: false
